export default [
    { Text: "Deep Learning", Value: 1 },
    { Text: "Desarrollo Web", Value: 1 },
    { Text: "Machine Learning", Value: 1 },
    { Text: "POO", Value: 1 },
    { Text: "Termocuplas", Value: 1 },
    { Text: "Control", Value: 1 },
    { Text: "Locomoción", Value: 4 },
    { Text: "Consola", Value: 1 },
    { Text: "Análisis de Datos", Value: 1 },
    { Text: "Python", Value: 1 },
    { Text: "Matlab", Value: 1 },
    { Text: "Cambio de Base", Value: 1 },
    { Text: "Estadistica Inferencial", Value: 1 },
    { Text: "Programación competitiva", Value: 1 },
    { Text: "Redes Neuronales", Value: 1 },
    { Text: "Habilidades Blandas", Value: 1 },
    { Text: "Dinamica", Value: 1 },
    { Text: "Métodos numéricos", Value: 2 },
    { Text: "Finanzas Personales", Value: 1 },
    { Text: "Salud en el trabajo", Value: 1 },
    { Text: "Equidad de genero", Value: 1 },
    { Text: "Arduino", Value: 4 },
    { Text: "Microcontroladores", Value: 4 }
  ];